spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  config:
#    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
    import: "optional:configserver:http://localhost:8888"
